-- ============================================================================
-- Kitify Solutions — warranty claims
-- Migration: 0009_claims
--
-- Closes the order → install → warranty → claim lifecycle. A claim always hangs off
-- an order (which already carries install_date, completion_photos, warranty_status and
-- warranty_registered_at from 0005), so the claim row only needs what's new: which
-- products are affected, the contractor's description + photos, and the review outcome.
--
-- claim_number is CLM-YYYYMM-NNNN, generated by a race-safe BEFORE INSERT trigger using
-- the same counter-table pattern as next_order_number() in 0005 — never set by the client.
--
-- RLS mirrors 0002/0003: the owner does everything on owner_id = auth.uid(); admins get
-- read access via public.is_admin(). Note that admins can SELECT but not UPDATE from the
-- browser client — the review/resolve actions land in a later admin task and will need
-- either an admin UPDATE policy or a service-role route.
--
-- Depends on 0001 (set_updated_at trigger fn), 0002 (is_admin helper) and 0005 (orders).
-- Re-runnable: IF NOT EXISTS / CREATE OR REPLACE / DROP … IF EXISTS throughout.
-- ============================================================================

create table if not exists public.claims (
  id                uuid primary key default gen_random_uuid(),
  order_id          uuid not null references public.orders (id),
  owner_id          uuid not null references public.profiles (id),
  claim_number      text unique not null,   -- CLM-YYYYMM-NNNN, set by the trigger below
  status            text not null default 'submitted'
                      check (status in ('submitted', 'under_review', 'approved', 'denied', 'resolved')),
  affected_products jsonb not null default '[]',  -- array of snapshot line-item keys
  description       text not null,
  photos            jsonb default '[]',           -- array of storage URLs
  resolution        text,
  admin_notes       text,
  submitted_at      timestamptz default now(),
  reviewed_at       timestamptz,
  resolved_at       timestamptz,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create index if not exists claims_order_id_idx on public.claims (order_id);
create index if not exists claims_owner_id_idx on public.claims (owner_id);

-- updated_at refresh (reuses the shared trigger function from 0001).
drop trigger if exists claims_set_updated_at on public.claims;
create trigger claims_set_updated_at
  before update on public.claims
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- Row Level Security — owner does everything, admin reads.
--
-- claims_owner is FOR ALL with only USING: Postgres reuses the USING expression as the
-- WITH CHECK expression when the latter is omitted, so inserts/updates are constrained
-- to owner_id = auth.uid() too.
-- ----------------------------------------------------------------------------
alter table public.claims enable row level security;

drop policy if exists "claims_owner" on public.claims;
create policy "claims_owner" on public.claims
  for all to authenticated
  using (owner_id = auth.uid());

drop policy if exists "claims_admin" on public.claims;
create policy "claims_admin" on public.claims
  for select to authenticated
  using (public.is_admin());

-- ----------------------------------------------------------------------------
-- Claim number generation — CLM-YYYYMM-NNNN, sequence resets each calendar month.
--
-- Same shape as next_order_number() (0005): a counter row per YYYYMM period, bumped
-- atomically via INSERT … ON CONFLICT DO UPDATE … RETURNING, which row-locks the period
-- so concurrent inserts serialize instead of colliding. SECURITY DEFINER + an empty
-- search_path so it can write the counter regardless of RLS and can't be hijacked.
-- ----------------------------------------------------------------------------
create table if not exists public.claim_number_counters (
  period   text primary key,           -- 'YYYYMM'
  last_seq integer not null default 0
);

-- RLS on with no policies → no client touches this table directly; only the SECURITY
-- DEFINER function (as owner) and service_role can.
alter table public.claim_number_counters enable row level security;

create or replace function public.next_claim_number()
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_period text := to_char(now(), 'YYYYMM');
  v_seq    integer;
begin
  insert into public.claim_number_counters as c (period, last_seq)
    values (v_period, 1)
  on conflict (period) do update
    set last_seq = c.last_seq + 1
  returning c.last_seq into v_seq;
  return 'CLM-' || v_period || '-' || lpad(v_seq::text, 4, '0');
end;
$$;

-- BEFORE INSERT: assign a claim number when the row doesn't already carry one. The
-- client never supplies claim_number, so it's always generated here — which is also why
-- the NOT NULL constraint is safe (it's checked after BEFORE triggers run).
create or replace function public.claims_set_claim_number()
returns trigger
language plpgsql
as $$
begin
  if new.claim_number is null or new.claim_number = '' then
    new.claim_number := public.next_claim_number();
  end if;
  return new;
end;
$$;

drop trigger if exists claims_set_claim_number on public.claims;
create trigger claims_set_claim_number
  before insert on public.claims
  for each row execute function public.claims_set_claim_number();
